pub const VENDOR_ID: u16 = 0x0483;
pub const PRODUCT_ID: u16 = 0x512a;
pub const INTERFACE_ID: i32 = 1;

#[repr(u16)]
pub enum OpCode {
    VersionRead = 0xf9,
    CounterRead = 0xe3,
    KeyLock = 0xd9,

    KeymapDataRead = 0xf2,
    KeymapDataStart = 0xf1,
    KeymapData = 0xf0,
    KeymapDataEnd = 0xf6,

    CalibInit = 0xdb,
    CalibPressed = 0xdd,
}

pub const HWCODE: [&str; 256] = [
    "unmapped",
    "ESC",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "BS",
    "TAB",
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    "[",
    "]",
    "\\",
    "Caps Lock",
    "A",
    "S",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    ";",
    "\'",
    "RET",
    "L-Shift",
    "Z",
    "X",
    "C",
    "V",
    "B",
    "N",
    "M",
    ",",
    ".",
    "/",
    "R-Shift",
    "L-CTRL",
    "Left-Super",
    "L-Alt",
    "Space",
    "R-Alt",
    "Right-Super",
    "ContextMenu",
    "R-Ctrl",
    "Wakeup",
    "Sleep",
    "Power",
    "PriSc",
    "SclLk",
    "Pause",
    "Ins",
    "Home",
    "PageUp",
    "Del",
    "End",
    "PageDown",
    "Up Arrow",
    "Left Arrow",
    "Down Arrow",
    "Right Arrow",
    "Num Lock",
    "(/)",
    "(*)",
    "(7)",
    "(8)",
    "(9)",
    "(4)",
    "(5)",
    "(6)",
    "(1)",
    "(2)",
    "(3)",
    "(0)",
    "(.)",
    "(-)",
    "(+)",
    "(Enter)",
    "Media Next Track",
    "Media Previous Track",
    "Media Stop",
    "Media Play/Pause",
    "Media Mute",
    "Media VolumeUp",
    "Media VolumeDn",
    "Media Select",
    "WWW Email",
    "Media Calculator",
    "Media My Computer",
    "WWW Search",
    "WWW Home",
    "WWW Back",
    "WWW Forward",
    "WWW Stop",
    "WWW Refresh",
    "WWW Favorites",
    "Mouse Mouse Left",
    "Mouse Mouse Right",
    "Mouse Mouse Up",
    "Mouse Mouse Down",
    "Mouse Key Left",
    "Mouse Key Right",
    "Mouse Key Middle",
    "Mouse Wheel Up",
    "Mouse Wheel Dn",
    "Backlight Switch",
    "Backlight Macro",
    "Demonstrate",
    "Star shower",
    "Riffle",
    "Demo Stop",
    "Breathe",
    "Breathe Sequence-",
    "Breathe Sequence+",
    "Backlight Lightness-",
    "Backlight Lightness+",
    "Sunset or Relax/Aurora",
    "Color Breathe",
    "Back Color Exchange",
    "Adjust Trigger Point",
    "Keyboard Lock",
    "Shift&Up",
    "Ctrl&Caps Exchange",
    "WinLock",
    "MouseLock",
    "Win/Mac Exchange",
    "R-Fn",
    "Mouse Unit Pixel",
    "Mouse Unit Time",
    "Programmable keyboard",
    "Backlight Record1",
    "Backlight Record2",
    "Backlight Record3",
    "Backlight Record4",
    "Backlight Record5",
    "Backlight Record6",
    "L-Fn",
    "Wire/Wireless exchange",
    "BTD1",
    "BTD2",
    "BTD3",
    "Game",
    "ECO",
    "Mouse First Delay",
    "Key Repeat Rate",
    "Key Response Delay",
    "USB Report Rate",
    "Key Scan Period",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "Mouse Left Double Click",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "<>|",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
];
